/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-11-02 17:12:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.entity.Founder;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/all_components/footer.jsp", Long.valueOf(1730004929091L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1730088445836L));
    _jspx_dependants.put("jar:file:/D:/Care%20India%20NGO%20Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Care-India/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("/all_components/allCss.jsp", Long.valueOf(1730527728412L));
    _jspx_dependants.put("/all_components/navbar.jsp", Long.valueOf(1730566627507L));
    _jspx_dependants.put("/all_components/indexCss.jsp", Long.valueOf(1730017694596L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.entity.Founder");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Payment Page</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Adding Bootstrap JS for interactivity -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/src/core.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\"></script>\r\n");
      out.write("<script src=\"path/to/core.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Index CSS</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("footer {\r\n");
      out.write("	background-color: #333;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 10px 0; /* Reduce padding for less height */\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	font-family: Cambria, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-content {\r\n");
      out.write("	max-width: 1200px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	padding: 0 10px; /* Reduce horizontal padding */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: space-around; /* Space sections evenly */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-section {\r\n");
      out.write("	flex: 1 1 200px; /* Allow sections to take up only necessary width */\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-section h5 .anchor {\r\n");
      out.write("	font-size: 1em; /* Smaller font size for title */\r\n");
      out.write("	margin-bottom: 8px; /* Reduce margin for more compact look */\r\n");
      out.write("	color: #007bff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .footer-section p, footer .footer-section a {\r\n");
      out.write("	font-size: 0.8em; /* Smaller font for text */\r\n");
      out.write("	color: #ccc;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	margin: 0; /* Remove additional margin */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer .social-icons a {\r\n");
      out.write("	color: #ccc;\r\n");
      out.write("	margin: 0 5px;\r\n");
      out.write("	font-size: 1em; /* Reduce icon size */\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* General styling */\r\n");
      out.write("body {\r\n");
      out.write("	background-image: url('images/background.jpg');\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-attachment: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body::before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	background-image: url('images/background.jpg');\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-attachment: fixed;\r\n");
      out.write("	filter: blur(50px); /* Adjust the blur level as needed */\r\n");
      out.write("	z-index: -1;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Main heading style */\r\n");
      out.write("h1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: grey;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 2em;\r\n");
      out.write("	font-family: Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Card styling */\r\n");
      out.write(".card {\r\n");
      out.write("	margin: 20px auto;\r\n");
      out.write("	border: none;\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	font-family: Cambria, sans-serif;\r\n");
      out.write("	transition: transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover {\r\n");
      out.write("	margin: 20px auto;\r\n");
      out.write("	border: none;\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Card image styling */\r\n");
      out.write(".card img {\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	transition: transform 0.5s ease, opacity 0.5s ease;\r\n");
      out.write("	border-radius: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Slide-in and slide-out animations */\r\n");
      out.write(".slide-in {\r\n");
      out.write("	transform: translateX(0);\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slide-out {\r\n");
      out.write("	transform: translateX(0);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive layout adjustments */\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("	.card {\r\n");
      out.write("		max-width: 700px;\r\n");
      out.write("	}\r\n");
      out.write("	.card .row {\r\n");
      out.write("		flex-direction: row;\r\n");
      out.write("	}\r\n");
      out.write("	.card img {\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		max-height: 250px;\r\n");
      out.write("	}\r\n");
      out.write("	h1 {\r\n");
      out.write("		font-size: 2.5em;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 767px) {\r\n");
      out.write("	.card {\r\n");
      out.write("		max-width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	.card .row {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("	}\r\n");
      out.write("	.card img {\r\n");
      out.write("		height: 200px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	h1 {\r\n");
      out.write("		font-size: 1.8em;\r\n");
      out.write("		margin-bottom: 15px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://checkout.razorpay.com/v1/checkout.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-image: url('images/background.jpg');\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-attachment: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body::before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	background-image: url('images/background.jpg');\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-attachment: fixed;\r\n");
      out.write("	filter: blur(50px);\r\n");
      out.write("	z-index: -1;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	max-width: 400px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	background-color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("	transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover {\r\n");
      out.write("	transform: scale(1.03);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-body {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-title {\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	font-family: Cambria, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#rzp-button1 {\r\n");
      out.write("	background-color: grey;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 12px 24px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#rzp-button1:hover {\r\n");
      out.write("	transform: scale(1.03);\r\n");
      out.write("	background-color: #59d9de;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"Content-Security-Policy\"\r\n");
      out.write("	content=\"script-src 'self' 'nonce-abc123' https://cdn.jsdelivr.net https://code.jquery.com https://stackpath.bootstrapcdn.com; object-src 'none';\">\r\n");
      out.write("\r\n");
      out.write("<title>Navbar</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Adding Bootstrap JS for interactivity -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/src/core.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\"></script>\r\n");
      out.write("<script src=\"path/to/core.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Add this CSS in your allCss.jsp file or within a <style> tag in your JSP file */\r\n");
      out.write(".navbar {\r\n");
      out.write("	font-family: 'Arial', sans-serif;\r\n");
      out.write("	font-size: 1.1em; /* Slightly increase font size */\r\n");
      out.write("	background-color: #f8f9fa; /* Light background */\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Add subtle shadow */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar .nav-link {\r\n");
      out.write("	color: grey; /* Default color for links */\r\n");
      out.write("	margin-right: 45px; /* Spacing between links */\r\n");
      out.write("	padding: 8px 12px; /* Increase padding */\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	margin-left: 25px;\r\n");
      out.write("	transition: color 0.3s ease, background-color 0.3s ease;\r\n");
      out.write("	/* Smooth transition */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar .nav-link:hover {\r\n");
      out.write("	color: white !important; /* Hover color for links */\r\n");
      out.write("	background-color: grey !important; /* Hover background */\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand img {\r\n");
      out.write("	width: 150px; /* Set fixed width */\r\n");
      out.write("	height: auto;\r\n");
      out.write("	margin-right: 100px !important; /* Space between logo and nav items */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-toggler {\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-success {\r\n");
      out.write("	color: #28a745; /* Green color */\r\n");
      out.write("	border-color: #28a745;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-success:hover {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #28a745; /* Green background on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive adjustments */\r\n");
      out.write("@media ( max-width : 767px) {\r\n");
      out.write("	.navbar-brand img {\r\n");
      out.write("		width: 120px;\r\n");
      out.write("	}\r\n");
      out.write("	.navbar .nav-link {\r\n");
      out.write("		font-size: 1em;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

	Founder founder = (Founder) session.getAttribute("userobj");
	
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<div class=\"navbar-brand\">\r\n");
      out.write("				<img src=\"images/logo.jpeg\" width=\"50%\" height=\"20%\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("				aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" aria-current=\"page\"\r\n");
      out.write("						href=\"about.jsp\">About</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" aria-current=\"page\"\r\n");
      out.write("						href=\"join_us.jsp\">Join Us</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" aria-current=\"page\"\r\n");
      out.write("						href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("					");

					if (founder == null) {
					
      out.write("\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" aria-current=\"page\"\r\n");
      out.write("						href=\"join_us.jsp\">Donate Now</a></li>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("				<form class=\"d-flex\">\r\n");
      out.write("					");

					if (founder != null) {
					
      out.write("\r\n");
      out.write("					<!-- Display Logout button and home button if logged in -->\r\n");
      out.write("					<a class=\"btn btn-outline-danger mr-3\" href=\"home.jsp\">Home</a> <a\r\n");
      out.write("						class=\"btn btn-outline-danger\" href=\"logout\">Logout</a>\r\n");
      out.write("					");

					} else {
					
      out.write("\r\n");
      out.write("					<!-- Display Founder login button if not logged in -->\r\n");
      out.write("					<a class=\"btn btn-outline-success\" href=\"founder_login.jsp\">Founder</a>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"card-container\">\r\n");
      out.write("		<div class=\"card\">\r\n");
      out.write("			<div class=\"card-body\">\r\n");
      out.write("				<h5 class=\"card-title\">Create a Difference</h5>\r\n");
      out.write("				<button id=\"rzp-button1\">Donate</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Hidden form to submit donation details to DonorServlet -->\r\n");
      out.write("	<form id=\"donorForm\" action=\"saveDonor\" method=\"post\"\r\n");
      out.write("		style=\"display: none;\">\r\n");
      out.write("		<input type=\"hidden\" name=\"name\" id=\"donorName\"> <input\r\n");
      out.write("			type=\"hidden\" name=\"email\" id=\"donorEmail\"> <input\r\n");
      out.write("			type=\"hidden\" name=\"amount\" id=\"donorAmount\"> <input\r\n");
      out.write("			type=\"hidden\" name=\"orderId\" id=\"donorOrderId\"> <input\r\n");
      out.write("			type=\"hidden\" name=\"paymentId\" id=\"donorPaymentId\">\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("        var options = {\r\n");
      out.write("            \"key\": \"rzp_test_EJIbfJyXtr3D6O\", // Enter the Key ID generated from Razorpay Dashboard\r\n");
      out.write("            \"amount\": \"");
      out.print((int) (Double.parseDouble(session.getAttribute("amount").toString())));
      out.write("\",\r\n");
      out.write("            \"currency\": \"INR\",\r\n");
      out.write("            \"name\": \"Care-India\",\r\n");
      out.write("            \"description\": \"Test Transaction\",\r\n");
      out.write("            \"order_id\": \"");
      out.print(request.getAttribute("orderId"));
      out.write("\",\r\n");
      out.write("            \"handler\": function(response) {\r\n");
      out.write("                // Populate hidden form with payment data\r\n");
      out.write("                document.getElementById('donorName').value = \"");
      out.print(request.getAttribute("name"));
      out.write("\";\r\n");
      out.write("                document.getElementById('donorEmail').value = \"");
      out.print(request.getAttribute("email"));
      out.write("\";\r\n");
      out.write("                document.getElementById('donorAmount').value = \"");
      out.print(request.getAttribute("amount"));
      out.write("\";\r\n");
      out.write("                document.getElementById('donorOrderId').value = \"");
      out.print(request.getAttribute("orderId"));
      out.write("\";\r\n");
      out.write("				document.getElementById('donorPaymentId').value = response.razorpay_payment_id;\r\n");
      out.write("\r\n");
      out.write("				// Submit form to DonorServlet\r\n");
      out.write("				document.getElementById('donorForm').submit();\r\n");
      out.write("			},\r\n");
      out.write("			\"theme\" : {\r\n");
      out.write("				\"color\" : \"#F37254\"\r\n");
      out.write("			}\r\n");
      out.write("		};\r\n");
      out.write("		var rzp1 = new Razorpay(options);\r\n");
      out.write("		document.getElementById('rzp-button1').onclick = function(e) {\r\n");
      out.write("			rzp1.open();\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Adding Bootstrap JS for interactivity -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/src/core.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\"></script>\r\n");
      out.write("<script src=\"path/to/core.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer-content\">\r\n");
      out.write("			<div class=\"footer-section\">\r\n");
      out.write("				<h5>\r\n");
      out.write("					<a href=\"about.jsp\" class=\"anchor\">About Us</a>\r\n");
      out.write("				</h5>\r\n");
      out.write("				<p>We are committed to supporting the underprivileged in our\r\n");
      out.write("					community through education, resources, and assistance for the\r\n");
      out.write("					elderly and disabled.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"footer-section\">\r\n");
      out.write("				<h5>\r\n");
      out.write("					<a href=\"contact.jsp\" class=\"anchor\">Contact Us</a>\r\n");
      out.write("				</h5>\r\n");
      out.write("				<p>Email: info@careIndia.org</p>\r\n");
      out.write("				<p>Phone: +91-7453527819</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"footer-section social-icons\">\r\n");
      out.write("				<h5 class=\"anchor\">Follow Us</h5>\r\n");
      out.write("				<a href=\"#\" target=\"_blank\" aria-label=\"Facebook\"><i\r\n");
      out.write("					class=\"fab fa-facebook-f\"></i></a> <a href=\"#\" target=\"_blank\"\r\n");
      out.write("					aria-label=\"Twitter\"><i class=\"fab fa-twitter\"></i></a> <a href=\"#\"\r\n");
      out.write("					target=\"_blank\" aria-label=\"Instagram\"><i\r\n");
      out.write("					class=\"fab fa-instagram\"></i></a> <a href=\"#\" target=\"_blank\"\r\n");
      out.write("					aria-label=\"LinkedIn\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<p>&copy; 2024 Care India Organization. All rights reserved.</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
